#
# Copyright (c) 2015 Daniel Reece - @HBRN8 - danielre@uk.ibm.com
#

beef:
    module:
        Wordpress_add_admin:
            enable: true
            category: "Persistence"
            name: "Wordpress Add Administrator"
            description: "This module stealthily adds a Wordpress administrator account"
            authors: ["hiburn8 @hbrn8"]
            target:
                 working: ["ALL"]